### ISSUE TITLE
Plotter tests are failing with attribute error

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1017]
## Describe the bug

The tests in `tests/display/test_plotter.py` fail with an `AttributeError`:
```log
E       AttributeError: module 'bluemira.geometry' has no attribute 'tools'
```

However, the tests do not fail if you run all the tests in the `display` directory, i.e., running the following the tests will pass.

```console
pytest tests/display/
```
Hence, this is not showing up in the CI.

I suspect some strange import shenanigans going on here.

## Steps to reproduce

```console
pytest tests/display/test_plotter.py
```

## Expected behaviour

Tests pass when only that test file is run.

**Comment by je-cook** [comment]
I can reproduce with these two lines:

```
In [1]: import bluemira.geometry as geo

In [2]: geo.tools
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <module>
----> 1 geo.tools

AttributeError: module 'bluemira.geometry' has no attribute 'tools'
```

I think this remanence of when we imported things into the __init__ in quite a few places. I think the fix is just replacing `import bluemira.geometry as geo` with `import bluemira.geometry.tools as tools` or similar. I'll put in a PR unless you've already got one going?

**Comment by hsaunders1904** [comment]
@je-cook I haven't started this yet, so I'm happy for you to open a PR
