### ISSUE TITLE
EU-DEMO parameter descriptions in the documentation are not working

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1252]
## Describe the bug

Try to access this page in the documentation: https://bluemira.readthedocs.io/en/develop/EU-DEMO_params.html

## Steps to reproduce

1. Access this page in the documentation: https://bluemira.readthedocs.io/en/develop/EU-DEMO_params.html
2. See this:

![image](https://user-images.githubusercontent.com/26097289/178774495-f0377393-fbff-4f8a-ae87-7d483c460132.png)

## Expected behaviour

I expect to be able to see a full list of the `Parameters` used.

## Environment (please complete the following information)

Online documentation. @je-cook also checked and the issue exists locally.

## Additional context
Technically at the moment this is for the EU-DEMO `Parameters`, but as this is changing, I would still want to be able to see all general parameters + those used exclusively for EU-DEMO.

**Comment by je-cook** [comment]
More info: 

We used to have all the variables of a reactor listed in the `default_params` variable of a reactor class. This was read in by sphinx here:
 https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/119fbfc36fd4f29e8d9570ad3cfa66a93d9a384d/documentation/source/conf.py#L112

This is no longer the case because of other changes but will probably be accessible again after #1192 is sorted but the above will need updating. See below for how it was used before:

https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/19052c102ec1f1a8e34b0df070efd418fd226999/documentation/source/EU-DEMO_params.rst

**Comment by je-cook** [comment]
Another option is we modify the function in `conf.py` to read from `Configuration` for now

**Comment by je-cook** [comment]
Remove for now we may put it back in when we have EUDEMO docs
