### ISSUE TITLE
Write configuration mangler

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1806]
## Description of issue / requirement to address

we should write a configuration json input file(s) processor to convert the json file into a more useable object than the default dictionary. 

## Proposed solution

Create an object to read in the json files and organise it into a structure the makes access simple eg

config.TF.params 
config.TF.designer
config.TF.builder

**Comment by oliverfunk** [comment]
@hsaunders1904 re. scoping of local/global params.

I would argue that it's better to give more specific params the ability overwrite less specific ones (like in CSS).

I.e. local overwrites global

This give more flexibility in my mind, but maybe it's not applicable here because by defining a global param, you want it to be global period.

A warning should defiantly be shown in either case.
