### ISSUE TITLE
bluemira is currently Ubuntu/Debian-centric

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#201]
In GitLab by @makeclean on Jun 15, 2021, 12:59

For a bunch of obvious historical reasons, BLUEPRINT is Ubuntu/Debian centric. In the long term it would be good to make BLUEPRINT a bit more agnostic in the OS. There are a few things that need to be tidied up, e.g. in the various build scripts there are a bunch of root level installs, which is a no-no - e.g. install-pyocc.sh.

**Comment by je-cook** [comment]
I'm going to call this 'done'. All of the main install scripts dont use anything like apt anymore, although we do use conda for the default install. 
The docker image (which is more of a testbed than ready for prime time) uses ubuntu as a base and therefore the install scripts use apt.
Also the process and openmc install scripts use apt but realistically people should probably be following their respective install instructions instead of ours.
