### ISSUE TITLE
Incorrect ordering of SextupleArc vertexes

### ISSUE THREAD

**Issue by James-M-Roff** [Fusion-Power-Plant-Framework/bluemira#2089]
## Describe the bug

The vertexes for a SextupleArc are not in order. See the diagram below.

## Steps to reproduce

```from bluemira.geometry.parameterisations import SextupleArc
import bluemira.display as display

from typing import Iterable
import matplotlib.pyplot as plt


def plot_2d_labelled(wire, ax=None):

    if ax is None:
        _, ax = plt.subplots()

    if isinstance(wire, Iterable):
        for w in wire:
            plot_2d_labelled(w, ax)
        return

    display.plot_2d(wire, ax=ax, show=False)
    for idx in range(0, wire.vertexes._array.shape[1]):
        x = wire.vertexes._array[0, idx]
        z = wire.vertexes._array[2, idx]
        ax.plot(x, z, 'bx')
        ax.text(x + 0.1, z + 0.1, idx, fontsize=10)


p = SextupleArc()

wire = p.create_shape()

plot_2d_labelled(wire)
plt.show(block=True)
```

## Expected behaviour

The vertexes should be ordered, so vertex 0 and 1 should be switched.

## Screenshots / Tracebacks

![SextupleVertexOrdering](https://user-images.githubusercontent.com/127396115/228283219-a2269568-48ac-4c0d-82d6-b3ae2fc8c801.png)

## Environment (please complete the following information)

- OS: Ubuntu 22.04.1 LTS
- Version: v1.1.0 (I think)
- Branch: develop

## Additional context

When drawing the individual arcs in the SextupleArc, the start and end point need to be reversed.

Attached is a set of possible minor modifications which fixes this bug.
([SextupleArc.patch](https://github.com/Fusion-Power-Plant-Framework/bluemira/files/11091003/SextupleArc.patch)
url)

**Comment by CoronelBuendia** [comment]
Hi @James-M-Roff, thank you for this. I can reproduce.

There is, I think, a slight optimism in the expected behaviour here. The vertices returned by `BluemiraWire.vertexes` make no claim to be "ordered", similarly there is no CCW/CW convention possible here, as not all wires are planar, and the underlying orientation can change as wires are used to create faces, shells, solids.

We do in fact wrap the ordered vertices, but these are not yet exposed on the `BluemiraWire` class, see below:

```python
    import bluemira.display as display
    from bluemira.geometry.parameterisations import SextupleArc
    from typing import Iterable
    import matplotlib.pyplot as plt
    from bluemira.codes._freecadapi import ordered_vertexes, vertexes


    def plot_2d_labelled(wire, ax=None):

        if ax is None:
            _, ax = plt.subplots()

        if isinstance(wire, Iterable):
            for w in wire:
                plot_2d_labelled(w, ax)
            return

        display.plot_2d(wire, ax=ax, show=False)
        verts = ordered_vertexes(wire.shape).T
        for idx in range(0, verts.shape[1]):
            x = verts[0, idx]
            z = verts[2, idx]
            ax.plot(x, z, 'bx')
            ax.text(x + 0.1, z + 0.1, idx, fontsize=10)


    p = SextupleArc()

    wire = p.create_shape()

    plot_2d_labelled(wire)
    plt.show(block=True)
```

![image](https://user-images.githubusercontent.com/26097289/228447281-12f8edcd-4de6-4620-b2c1-065b03fb5a65.png)

Note that these vertices end up being arranged CCW in this set of inputs, but this is not something that should be relied on. If you need to reliably extract specific sub-wires, you are best off accessing these via their labels.

What we can do is expose an `ordered_vertexes` property on `BluemiraWire`, but if for whatever reason you do require them to be reliably arranged in a particular CCW/CW convention, I can only offer (in future) the following:

```python
verts = wire.ordered_vertexes
verts.set_ccw([0, -1, 0])  # or [0, 1, 0]
```

I will confer with @ivanmaione to see if the edges and vertices that we return should always be ordered, or if we want to expose both approaches to the user.
