### ISSUE TITLE
Refactor `equilibria/coils.py`

### ISSUE THREAD

**Issue by alexanderianblair** [Fusion-Power-Plant-Framework/bluemira#346]
## Description of issue / requirement to address

Implement the general refactor of `coils.py` as discussed on MIRO:

![image](https://user-images.githubusercontent.com/26097289/153381175-2443a98a-d3ba-4a13-bb53-eaf87b9e64d7.png)

The general ideas are as follows:
* `CoilGroup` shall be the new base class object, which `Coil`, `Circuit`, `SymmetricCircuit` and `CoilSet` inherit from
* A new mixin class shall be used to isolate all physical calculations associated with the existence of a `CoilGroup` (psi, Bx, Bz, etc.)
* `CoilGroup` shall remain ignorant of how they are being controlled or size-fixed
* `CoilSet` will be responsible for the control and size-fixing of coils, and have some utility methods for extracting useful subsets of coils inside the underlying `CoilGroup`

Now `SymmetricCircuit` inherits from `CoilGroup` objects, `CoilGroup` objects now may contain a mixture of `Coil` and `CoilGroup` objects within them, which each have their own (distinct) set of methods and attributes. This has introduced bugs such as #322 arising from calling methods and attributes existing in `Coil` objects that do not exist in `CoilGroup `objects. 

## Proposed solution

If `Coil` is made to inherit from `CoilGroup` as a special case (of size 1), then it can be assumed that all `CoilGroup` objects contain only `CoilGroup` objects of smaller size.

## Alternative solutions
`Coil` properties could be added separately to `SymmetricCircuit`, or all existing implementations updated to allow for either `Coil` or `CoilGroup` objects being present in `CoilGroup` objects. This would make the code more fragile when changes are made to how the coilset is handled.

**Comment by sebkahn** [comment]
Hello

This issue should address the STEP reactor design issue forcing us to re-create `Coils` and `Coilsets` instead of updating them. The position not being propagated to the 2D shapes.

@CoronelBuendia suggested it was related to the coil corners not being updated and @alexanderianblair suggested another issue for the coil meshing.

Question: why storing the corners? Could we calculated them only when we want to output them? Having the coil position and its size should be enough to define its geometry, no?

The solution propose by everyone is do define accessors for both `Coil` and `SymmetricCircuits`, setters and getters that ensure all the coil consistuent are updated consistently.

A good test for this issue PR is to have STEP reactor design having its `Coil`s updated instead of re-created when modified and still having a working setup.
