### ISSUE TITLE
Plasmod mock run fails

### ISSUE THREAD

**Issue by ivanmaione** [Fusion-Power-Plant-Framework/bluemira#560]
## Describe the bug
Running Plasmod in mock, the following error is returned:
`bluemira.codes.error.CodesError: PLASMOD error: Abnormal paramters, possibly dtmax/dtmin too large`

## Steps to reproduce
Run `bluemira/examples/codes/run_plasmod_examples.py` using `build_config['mode'] = 'mock'`

## Expected behaviour

Read the mock plasma outputs stored in the working folder without error

## Environment (please complete the following information)

- OS: [macOs]
- Version [10.13.6]
- Branch [develop]

## Additional context
The problem is probably due to the fact that the variable `i_flag` is not correctly initialized during mock-Teardown.

## Possible solution
In `codes/plasmod/api.py` modify `Teardown._mock` function as follows
```python
    def _mock(self):
        """
        Mock plasmod teardown
        """
        self.io_manager = Outputs()
        self.io_manager.i_flag = 1
        self.io_manager.read_output_files(
            Path(self._run_dir, self.parent.setup_obj.output_file),
            Path(self._run_dir, self.parent.setup_obj.profiles_file),
        )
        self.prepare_outputs()
```

**Comment by je-cook** [comment]
The error I get is `FileNotFoundError: [Errno 2] No such file or directory: 'plasmod_outputs.dat'`. I think I forgot to create a mock output file. 
If I have an already passing 'plasmod_output.dat' file (one where i_flag==1) it works fine for me running the example script in run mode and then in mock mode.

As an aside this could be combined with a read mode to allow reading of existing output files (which I havent written yet). I will wait until fabrizio's io file parsing and updated mappings are in. 

In theory the current mock mode does that...but probably should be explicit.

Maybe also any read mode should just warn rather than error if the i_flag is in an error state

**Comment by ivanmaione** [comment]
Hi @je-cook, thanks for the clarification. I am going to close this issue and just open a request for the creation of a mock example with plasmod.
