### ISSUE TITLE
Review of builder functionality

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#629]
## Description of issue / requirement to address

We've used the new builders /design framework for a while now, so it would be good to have a review of what is working well and what could do with a clean up or further improvements. I've put this ticket in to facilitate some discussion around that.

@CoronelBuendia - you've probably used the design / builders stuff the most other than me, so would appreciate any other thoughts you might have.

## Proposed solution

TBD

**Comment by DanShort12** [comment]
1. We seem to be keeping to separation of concerns fairly well, and I like how the logic for making the geometry is separated out from the solving of optimisation problems / reading previous result / mocking. It could be useful to break some of the build functions down further so that there are individual functions for each component.

2. The callable logic on builders can be a bit fiddly, and as seen in #589 this can lead to some complications when arguments need to be passed to one method but not another. It may be worth unwinding this and just having the user make separate calls to the relevant methods (at least until there are enough examples to factor the problem back down into a form that works in all cases).

3. Related to 2., we're currently doing quite a bit that hides the real signatures of the builder methods. This leads to too much use of `**kwargs` and results in it being unclear how a method should be called because e.g. the IDE doesn't know what arguments can be passed in, or what help text is available. I think this is one of the main issues at the moment, and probably warrants some of this being unwound.

4. The run/read/mock can be a bit tricky to use when arguments need to be passed into the design problem. This leads tothe different modes needing to be called differently, which then ends up hiding what's needed for the actual method from the user (as for 3. this is seen in a resulting proliferation of `**kwargs` to cope with this).

I think my main gripe from the points I've listed so far is that we're doing quite a bit to hide functionality from the user, which results in the usage being obscured or at least hard to discover e.g. in an IDE.

**Comment by CoronelBuendia** [comment]
I completely agree with your points 2, 3, and 4. The main problem is that it is at present difficult to unpick the logic of what arguments are getting used where. I fear doing everything in a `kwargs` dict is not going to be sustainable, long-term.

The real signatures are obfuscated, and a lot of logic happens quite deep under the hood in various abstractions. The result is (because I still unfamiliar with this arhitecture) that I have to click through all of the subclasses and private methods every time in order to check it will do what I hope.

I think the priority should remain "ease of use" for the average user, who might want to change some problem settings or parameterisation, etc. But we should consider "ease of developer use" in terms of writing new `Builders` and the like. Sadly, I don't have any immediate suggestions on how to improve things!

**Comment by DanShort12** [comment]
I thought a bit about this and I think moving more stuff into the initialisation of the classes could help. My feeling is that this would mean that at least the interface for running the build would be similar for different builders - that's what caused some real stuttering with the thermal shield build (at least from my poking). We're also doing a bit of work to preempt the repetition of builds but we're not actually doing that yet, so perhaps some of the reinitialisation logic can be simplified for now, and we can just make a new instance of the builder and e.g. track generations if we need to do that (but again, we'd just get one generation of everything for now).
